name: LaTeX PDF generator
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: "resume.tex"
          glob_root_file: true
          
      - name: Upload PDF file
        uses: actions/upload-artifact@master
        with:
          name: PDF
          path: main.pdf